Fix/update example for react-native
Trying to use createReducer caused:
TypeError: undefined is not a function (evaluating 'navigationStore.getStateForAction(action, state)')

Also, instead of getSceneStyle there is now sceneStyle which expects a Style.